%YAML:1.0

# Camera calibration and distortion parameters (OpenCV)
File.version: "1.0"

Camera.type: "PinHole"

Camera1.fx: 568.378052
Camera1.fy: 555.940430
Camera1.cx: 424.178429
Camera1.cy: 256.296124

Camera1.k1: 0.021785
Camera1.k2: -0.001529
Camera1.p1: 0.005854
Camera1.p2: -0.001099
Camera1.k3: 0.0

Camera.width: 856
Camera.height: 480

# Camera frames per second
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1





#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 458.654
Camera1.fy: 457.296
Camera1.cx: 367.215
Camera1.cy: 248.375

Camera1.k1: -0.28340811
Camera1.k2: 0.07395907
Camera1.p1: 0.00019359
Camera1.p2: 1.76187114e-05

# Camera resolution
Camera.width: 856
Camera.height: 480



# 856 , 480
Camera.newWidth: 856
Camera.newHeight: 480

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1



# Transformation from camera to body-frame (imu)
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   # data: [  0.0000000, 0.0000000,  1.0000000,  0.0000000,
   #          1.0000000,  0.0000000, 0.0000000,  0.0000000,
   #          0.0000000,  1.0000000, 0.0000000,  0.0,
   #          0.         , 0.        ,  0.         , 1.]
   # data: [ 1.0000000, 0.0000000,  0.0000000,  0.0000000,
   #       0.0000000,  1.0000000, 0.0000000,  0.0000000,
   #       0.0000000,  0.0000000, 1.0000000,  0.0,
   #       0.         , 0.        ,  0.         , 1.]
   data: [  0.0000000, -1.0000000,  0.0000000,  0.0000000,
         1.0000000,  0.0000000, 0.0000000,  0.0000000,
         0.0000000,  0.0000000, 1.0000000,  0.0,
         0.         , 0.        ,  0.         , 1.]
   # data: [  0.0000000, -1.0000000,  0.0000000,  0.0000000,
   #         -0.2246836,  0.0000000, -0.9744318,0.022,
   #          0.9744318,  0.0000000, -0.2246836,-0.097,
   #          0.         , 0.        ,  0.         , 1.]
   # data: [  0.12718268 , 0.20235269, -0.97101903, -0.09916513,
   #          0.99187525, -0.02874785 , 0.12392357 , 0.01272143,
   #         -0.00283844, -0.97889067, -0.20436486 , 0.00210755,
   #          0.         , 0.        ,  0.         , 1.        ]

# IMU noise
IMU.NoiseGyro: 1.7e-4 #1.6968e-04
IMU.NoiseAcc: 2.0000e-3 #2.0e-3
IMU.GyroWalk: 1.9393e-05 
IMU.AccWalk: 3.0000e-03 # 3e-03
IMU.Frequency: 30.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000 # 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -1.7
Viewer.ViewpointZ: 0.8
Viewer.ViewpointF: -500.0


# System.SaveAtlasToFile: "demo"
# System.LoadAtlasFromFile: "demo4"
# System.loopClosing: 1